"""empty message

Revision ID: 28a719de7ec9
Revises: ce63548f31e6
Create Date: 2024-08-26 08:31:54.201368

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28a719de7ec9"
down_revision = "ce63548f31e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reviewers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("webpage_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webpage_id"],
            ["webpages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("stakeholders")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stakeholders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "webpage_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="stakeholders_user_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["webpage_id"],
            ["webpages.id"],
            name="stakeholders_webpage_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="stakeholders_pkey"),
    )
    op.drop_table("reviewers")
    # ### end Alembic commands ###
