"""empty message

Revision ID: 2cebdd533a59
Revises: 0bd6fd83b781
Create Date: 2024-10-24 13:52:16.788586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cebdd533a59'
down_revision = '0bd6fd83b781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_tasks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
