"""empty message

Revision ID: 7b0c727c0201
Revises: c4073a9759fc
Create Date: 2024-09-19 10:41:48.215628

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b0c727c0201"
down_revision = "c4073a9759fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jira_tasks", schema=None) as batch_op:
        batch_op.alter_column(
            "jira_id",
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jira_tasks", schema=None) as batch_op:
        batch_op.alter_column(
            "jira_id",
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
